pipeline {
    agent any

    stages {
        stage('CLONE')
        {
        steps{
            git branch : 'release-back', credentialsId : 'lancelot1672' ,url : 'https://lab.ssafy.com/s08-blockchain-nft-sub2/S08P22B210.git'
        }
           
        }
        
        stage('BUILD')
        {
            steps
            {
            sh '''
            cd back
            chmod +x gradlew
            ./gradlew clean build

            '''
            }
            
        }
         stage('DOCKER BUILD')
        {
            steps
            {
            sh '''
            cd /var/jenkins_home/workspace/ttocket_test/back
            docker build -t ttocket/spring-back-end:1 .
            '''
            }
           
        }
        
        stage('DEPLOY')
        {
            steps
            {
            sh '''
             docker stop spring-container
            docker rm spring-container
            echo 'Remove if spring-container exist'

            
            docker run --name spring-container -d -p 8080:8080 ttocket/spring-back-end:1 
            echo 'Success'
            '''
            }
           
        }
    }
}